- name: "start iis service"
  hosts: app
  become: yes
  become_user: jits
  gather_facts: false
  vars:
    - W3SVC
    - Themes

  tasks:
    - name: "Get service status"
      win_service:
        name: "{{ item }}"
      register: services_status
      loop: "{{ service_start }}"

    - name: "starting iis service"
      win_service:
        name: "{{ item.name }}"
        state: started
      loop: "{{ services_status.results }}"
      when: item.state == 'stopped'
